/**
 * generated by Xtext 2.25.0
 */
package assignment2.gameDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Cell</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link assignment2.gameDSL.Cell#getCoordinates <em>Coordinates</em>}</li>
 *   <li>{@link assignment2.gameDSL.Cell#getCellType <em>Cell Type</em>}</li>
 * </ul>
 *
 * @see assignment2.gameDSL.GameDSLPackage#getCell()
 * @model
 * @generated
 */
public interface Cell extends EObject
{
  /**
   * Returns the value of the '<em><b>Coordinates</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Coordinates</em>' containment reference.
   * @see #setCoordinates(Coordinates)
   * @see assignment2.gameDSL.GameDSLPackage#getCell_Coordinates()
   * @model containment="true"
   * @generated
   */
  Coordinates getCoordinates();

  /**
   * Sets the value of the '{@link assignment2.gameDSL.Cell#getCoordinates <em>Coordinates</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Coordinates</em>' containment reference.
   * @see #getCoordinates()
   * @generated
   */
  void setCoordinates(Coordinates value);

  /**
   * Returns the value of the '<em><b>Cell Type</b></em>' attribute.
   * The literals are from the enumeration {@link assignment2.gameDSL.CellType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cell Type</em>' attribute.
   * @see assignment2.gameDSL.CellType
   * @see #setCellType(CellType)
   * @see assignment2.gameDSL.GameDSLPackage#getCell_CellType()
   * @model
   * @generated
   */
  CellType getCellType();

  /**
   * Sets the value of the '{@link assignment2.gameDSL.Cell#getCellType <em>Cell Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cell Type</em>' attribute.
   * @see assignment2.gameDSL.CellType
   * @see #getCellType()
   * @generated
   */
  void setCellType(CellType value);

} // Cell
