/**
 * generated by Xtext 2.25.0
 */
package assignment2.gameDSL;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see assignment2.gameDSL.GameDSLFactory
 * @model kind="package"
 * @generated
 */
public interface GameDSLPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "gameDSL";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.GameDSL.assignment2";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "gameDSL";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  GameDSLPackage eINSTANCE = assignment2.gameDSL.impl.GameDSLPackageImpl.init();

  /**
   * The meta object id for the '{@link assignment2.gameDSL.impl.GameImpl <em>Game</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see assignment2.gameDSL.impl.GameImpl
   * @see assignment2.gameDSL.impl.GameDSLPackageImpl#getGame()
   * @generated
   */
  int GAME = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME__NAME = 0;

  /**
   * The feature id for the '<em><b>Grid</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME__GRID = 1;

  /**
   * The feature id for the '<em><b>Rules</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME__RULES = 2;

  /**
   * The number of structural features of the '<em>Game</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link assignment2.gameDSL.impl.GridImpl <em>Grid</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see assignment2.gameDSL.impl.GridImpl
   * @see assignment2.gameDSL.impl.GameDSLPackageImpl#getGrid()
   * @generated
   */
  int GRID = 1;

  /**
   * The feature id for the '<em><b>Size</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRID__SIZE = 0;

  /**
   * The feature id for the '<em><b>State</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRID__STATE = 1;

  /**
   * The number of structural features of the '<em>Grid</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRID_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link assignment2.gameDSL.impl.SizeImpl <em>Size</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see assignment2.gameDSL.impl.SizeImpl
   * @see assignment2.gameDSL.impl.GameDSLPackageImpl#getSize()
   * @generated
   */
  int SIZE = 2;

  /**
   * The feature id for the '<em><b>Rows</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIZE__ROWS = 0;

  /**
   * The feature id for the '<em><b>Columns</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIZE__COLUMNS = 1;

  /**
   * The number of structural features of the '<em>Size</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIZE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link assignment2.gameDSL.impl.StateImpl <em>State</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see assignment2.gameDSL.impl.StateImpl
   * @see assignment2.gameDSL.impl.GameDSLPackageImpl#getState()
   * @generated
   */
  int STATE = 3;

  /**
   * The feature id for the '<em><b>Alives</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE__ALIVES = 0;

  /**
   * The number of structural features of the '<em>State</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link assignment2.gameDSL.impl.CellImpl <em>Cell</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see assignment2.gameDSL.impl.CellImpl
   * @see assignment2.gameDSL.impl.GameDSLPackageImpl#getCell()
   * @generated
   */
  int CELL = 4;

  /**
   * The feature id for the '<em><b>Coordinates</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CELL__COORDINATES = 0;

  /**
   * The feature id for the '<em><b>Cell Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CELL__CELL_TYPE = 1;

  /**
   * The number of structural features of the '<em>Cell</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CELL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link assignment2.gameDSL.impl.CoordinatesImpl <em>Coordinates</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see assignment2.gameDSL.impl.CoordinatesImpl
   * @see assignment2.gameDSL.impl.GameDSLPackageImpl#getCoordinates()
   * @generated
   */
  int COORDINATES = 5;

  /**
   * The feature id for the '<em><b>Row</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COORDINATES__ROW = 0;

  /**
   * The feature id for the '<em><b>Column</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COORDINATES__COLUMN = 1;

  /**
   * The number of structural features of the '<em>Coordinates</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COORDINATES_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link assignment2.gameDSL.impl.RuleImpl <em>Rule</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see assignment2.gameDSL.impl.RuleImpl
   * @see assignment2.gameDSL.impl.GameDSLPackageImpl#getRule()
   * @generated
   */
  int RULE = 6;

  /**
   * The feature id for the '<em><b>Condition</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__CONDITION = 0;

  /**
   * The feature id for the '<em><b>Amount</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__AMOUNT = 1;

  /**
   * The feature id for the '<em><b>Action</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__ACTION = 2;

  /**
   * The number of structural features of the '<em>Rule</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link assignment2.gameDSL.CellType <em>Cell Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see assignment2.gameDSL.CellType
   * @see assignment2.gameDSL.impl.GameDSLPackageImpl#getCellType()
   * @generated
   */
  int CELL_TYPE = 7;

  /**
   * The meta object id for the '{@link assignment2.gameDSL.Action <em>Action</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see assignment2.gameDSL.Action
   * @see assignment2.gameDSL.impl.GameDSLPackageImpl#getAction()
   * @generated
   */
  int ACTION = 8;

  /**
   * The meta object id for the '{@link assignment2.gameDSL.Condition <em>Condition</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see assignment2.gameDSL.Condition
   * @see assignment2.gameDSL.impl.GameDSLPackageImpl#getCondition()
   * @generated
   */
  int CONDITION = 9;


  /**
   * Returns the meta object for class '{@link assignment2.gameDSL.Game <em>Game</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Game</em>'.
   * @see assignment2.gameDSL.Game
   * @generated
   */
  EClass getGame();

  /**
   * Returns the meta object for the attribute '{@link assignment2.gameDSL.Game#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see assignment2.gameDSL.Game#getName()
   * @see #getGame()
   * @generated
   */
  EAttribute getGame_Name();

  /**
   * Returns the meta object for the containment reference '{@link assignment2.gameDSL.Game#getGrid <em>Grid</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Grid</em>'.
   * @see assignment2.gameDSL.Game#getGrid()
   * @see #getGame()
   * @generated
   */
  EReference getGame_Grid();

  /**
   * Returns the meta object for the containment reference list '{@link assignment2.gameDSL.Game#getRules <em>Rules</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Rules</em>'.
   * @see assignment2.gameDSL.Game#getRules()
   * @see #getGame()
   * @generated
   */
  EReference getGame_Rules();

  /**
   * Returns the meta object for class '{@link assignment2.gameDSL.Grid <em>Grid</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Grid</em>'.
   * @see assignment2.gameDSL.Grid
   * @generated
   */
  EClass getGrid();

  /**
   * Returns the meta object for the containment reference '{@link assignment2.gameDSL.Grid#getSize <em>Size</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Size</em>'.
   * @see assignment2.gameDSL.Grid#getSize()
   * @see #getGrid()
   * @generated
   */
  EReference getGrid_Size();

  /**
   * Returns the meta object for the containment reference '{@link assignment2.gameDSL.Grid#getState <em>State</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>State</em>'.
   * @see assignment2.gameDSL.Grid#getState()
   * @see #getGrid()
   * @generated
   */
  EReference getGrid_State();

  /**
   * Returns the meta object for class '{@link assignment2.gameDSL.Size <em>Size</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Size</em>'.
   * @see assignment2.gameDSL.Size
   * @generated
   */
  EClass getSize();

  /**
   * Returns the meta object for the attribute '{@link assignment2.gameDSL.Size#getRows <em>Rows</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Rows</em>'.
   * @see assignment2.gameDSL.Size#getRows()
   * @see #getSize()
   * @generated
   */
  EAttribute getSize_Rows();

  /**
   * Returns the meta object for the attribute '{@link assignment2.gameDSL.Size#getColumns <em>Columns</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Columns</em>'.
   * @see assignment2.gameDSL.Size#getColumns()
   * @see #getSize()
   * @generated
   */
  EAttribute getSize_Columns();

  /**
   * Returns the meta object for class '{@link assignment2.gameDSL.State <em>State</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>State</em>'.
   * @see assignment2.gameDSL.State
   * @generated
   */
  EClass getState();

  /**
   * Returns the meta object for the containment reference list '{@link assignment2.gameDSL.State#getAlives <em>Alives</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Alives</em>'.
   * @see assignment2.gameDSL.State#getAlives()
   * @see #getState()
   * @generated
   */
  EReference getState_Alives();

  /**
   * Returns the meta object for class '{@link assignment2.gameDSL.Cell <em>Cell</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Cell</em>'.
   * @see assignment2.gameDSL.Cell
   * @generated
   */
  EClass getCell();

  /**
   * Returns the meta object for the containment reference '{@link assignment2.gameDSL.Cell#getCoordinates <em>Coordinates</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Coordinates</em>'.
   * @see assignment2.gameDSL.Cell#getCoordinates()
   * @see #getCell()
   * @generated
   */
  EReference getCell_Coordinates();

  /**
   * Returns the meta object for the attribute '{@link assignment2.gameDSL.Cell#getCellType <em>Cell Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Cell Type</em>'.
   * @see assignment2.gameDSL.Cell#getCellType()
   * @see #getCell()
   * @generated
   */
  EAttribute getCell_CellType();

  /**
   * Returns the meta object for class '{@link assignment2.gameDSL.Coordinates <em>Coordinates</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Coordinates</em>'.
   * @see assignment2.gameDSL.Coordinates
   * @generated
   */
  EClass getCoordinates();

  /**
   * Returns the meta object for the attribute '{@link assignment2.gameDSL.Coordinates#getRow <em>Row</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Row</em>'.
   * @see assignment2.gameDSL.Coordinates#getRow()
   * @see #getCoordinates()
   * @generated
   */
  EAttribute getCoordinates_Row();

  /**
   * Returns the meta object for the attribute '{@link assignment2.gameDSL.Coordinates#getColumn <em>Column</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Column</em>'.
   * @see assignment2.gameDSL.Coordinates#getColumn()
   * @see #getCoordinates()
   * @generated
   */
  EAttribute getCoordinates_Column();

  /**
   * Returns the meta object for class '{@link assignment2.gameDSL.Rule <em>Rule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rule</em>'.
   * @see assignment2.gameDSL.Rule
   * @generated
   */
  EClass getRule();

  /**
   * Returns the meta object for the attribute '{@link assignment2.gameDSL.Rule#getCondition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Condition</em>'.
   * @see assignment2.gameDSL.Rule#getCondition()
   * @see #getRule()
   * @generated
   */
  EAttribute getRule_Condition();

  /**
   * Returns the meta object for the attribute '{@link assignment2.gameDSL.Rule#getAmount <em>Amount</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Amount</em>'.
   * @see assignment2.gameDSL.Rule#getAmount()
   * @see #getRule()
   * @generated
   */
  EAttribute getRule_Amount();

  /**
   * Returns the meta object for the attribute '{@link assignment2.gameDSL.Rule#getAction <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Action</em>'.
   * @see assignment2.gameDSL.Rule#getAction()
   * @see #getRule()
   * @generated
   */
  EAttribute getRule_Action();

  /**
   * Returns the meta object for enum '{@link assignment2.gameDSL.CellType <em>Cell Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Cell Type</em>'.
   * @see assignment2.gameDSL.CellType
   * @generated
   */
  EEnum getCellType();

  /**
   * Returns the meta object for enum '{@link assignment2.gameDSL.Action <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Action</em>'.
   * @see assignment2.gameDSL.Action
   * @generated
   */
  EEnum getAction();

  /**
   * Returns the meta object for enum '{@link assignment2.gameDSL.Condition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Condition</em>'.
   * @see assignment2.gameDSL.Condition
   * @generated
   */
  EEnum getCondition();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  GameDSLFactory getGameDSLFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link assignment2.gameDSL.impl.GameImpl <em>Game</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see assignment2.gameDSL.impl.GameImpl
     * @see assignment2.gameDSL.impl.GameDSLPackageImpl#getGame()
     * @generated
     */
    EClass GAME = eINSTANCE.getGame();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GAME__NAME = eINSTANCE.getGame_Name();

    /**
     * The meta object literal for the '<em><b>Grid</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GAME__GRID = eINSTANCE.getGame_Grid();

    /**
     * The meta object literal for the '<em><b>Rules</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GAME__RULES = eINSTANCE.getGame_Rules();

    /**
     * The meta object literal for the '{@link assignment2.gameDSL.impl.GridImpl <em>Grid</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see assignment2.gameDSL.impl.GridImpl
     * @see assignment2.gameDSL.impl.GameDSLPackageImpl#getGrid()
     * @generated
     */
    EClass GRID = eINSTANCE.getGrid();

    /**
     * The meta object literal for the '<em><b>Size</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GRID__SIZE = eINSTANCE.getGrid_Size();

    /**
     * The meta object literal for the '<em><b>State</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GRID__STATE = eINSTANCE.getGrid_State();

    /**
     * The meta object literal for the '{@link assignment2.gameDSL.impl.SizeImpl <em>Size</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see assignment2.gameDSL.impl.SizeImpl
     * @see assignment2.gameDSL.impl.GameDSLPackageImpl#getSize()
     * @generated
     */
    EClass SIZE = eINSTANCE.getSize();

    /**
     * The meta object literal for the '<em><b>Rows</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SIZE__ROWS = eINSTANCE.getSize_Rows();

    /**
     * The meta object literal for the '<em><b>Columns</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SIZE__COLUMNS = eINSTANCE.getSize_Columns();

    /**
     * The meta object literal for the '{@link assignment2.gameDSL.impl.StateImpl <em>State</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see assignment2.gameDSL.impl.StateImpl
     * @see assignment2.gameDSL.impl.GameDSLPackageImpl#getState()
     * @generated
     */
    EClass STATE = eINSTANCE.getState();

    /**
     * The meta object literal for the '<em><b>Alives</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATE__ALIVES = eINSTANCE.getState_Alives();

    /**
     * The meta object literal for the '{@link assignment2.gameDSL.impl.CellImpl <em>Cell</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see assignment2.gameDSL.impl.CellImpl
     * @see assignment2.gameDSL.impl.GameDSLPackageImpl#getCell()
     * @generated
     */
    EClass CELL = eINSTANCE.getCell();

    /**
     * The meta object literal for the '<em><b>Coordinates</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CELL__COORDINATES = eINSTANCE.getCell_Coordinates();

    /**
     * The meta object literal for the '<em><b>Cell Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CELL__CELL_TYPE = eINSTANCE.getCell_CellType();

    /**
     * The meta object literal for the '{@link assignment2.gameDSL.impl.CoordinatesImpl <em>Coordinates</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see assignment2.gameDSL.impl.CoordinatesImpl
     * @see assignment2.gameDSL.impl.GameDSLPackageImpl#getCoordinates()
     * @generated
     */
    EClass COORDINATES = eINSTANCE.getCoordinates();

    /**
     * The meta object literal for the '<em><b>Row</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COORDINATES__ROW = eINSTANCE.getCoordinates_Row();

    /**
     * The meta object literal for the '<em><b>Column</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COORDINATES__COLUMN = eINSTANCE.getCoordinates_Column();

    /**
     * The meta object literal for the '{@link assignment2.gameDSL.impl.RuleImpl <em>Rule</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see assignment2.gameDSL.impl.RuleImpl
     * @see assignment2.gameDSL.impl.GameDSLPackageImpl#getRule()
     * @generated
     */
    EClass RULE = eINSTANCE.getRule();

    /**
     * The meta object literal for the '<em><b>Condition</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RULE__CONDITION = eINSTANCE.getRule_Condition();

    /**
     * The meta object literal for the '<em><b>Amount</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RULE__AMOUNT = eINSTANCE.getRule_Amount();

    /**
     * The meta object literal for the '<em><b>Action</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RULE__ACTION = eINSTANCE.getRule_Action();

    /**
     * The meta object literal for the '{@link assignment2.gameDSL.CellType <em>Cell Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see assignment2.gameDSL.CellType
     * @see assignment2.gameDSL.impl.GameDSLPackageImpl#getCellType()
     * @generated
     */
    EEnum CELL_TYPE = eINSTANCE.getCellType();

    /**
     * The meta object literal for the '{@link assignment2.gameDSL.Action <em>Action</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see assignment2.gameDSL.Action
     * @see assignment2.gameDSL.impl.GameDSLPackageImpl#getAction()
     * @generated
     */
    EEnum ACTION = eINSTANCE.getAction();

    /**
     * The meta object literal for the '{@link assignment2.gameDSL.Condition <em>Condition</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see assignment2.gameDSL.Condition
     * @see assignment2.gameDSL.impl.GameDSLPackageImpl#getCondition()
     * @generated
     */
    EEnum CONDITION = eINSTANCE.getCondition();

  }

} //GameDSLPackage
