/**
 * generated by Xtext 2.25.0
 */
package assignment2.gameDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>State</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link assignment2.gameDSL.State#getAlives <em>Alives</em>}</li>
 * </ul>
 *
 * @see assignment2.gameDSL.GameDSLPackage#getState()
 * @model
 * @generated
 */
public interface State extends EObject
{
  /**
   * Returns the value of the '<em><b>Alives</b></em>' containment reference list.
   * The list contents are of type {@link assignment2.gameDSL.Cell}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Alives</em>' containment reference list.
   * @see assignment2.gameDSL.GameDSLPackage#getState_Alives()
   * @model containment="true"
   * @generated
   */
  EList<Cell> getAlives();

} // State
