/*
 * generated by Xtext 2.25.0
 */
package assignment2.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractGameDSLScopeProvider extends DelegatingScopeProvider {
}
