/**
 * generated by Xtext 2.25.0
 */
package assignment2.ide;

import assignment2.GameDSLRuntimeModule;
import assignment2.GameDSLStandaloneSetup;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class GameDSLIdeSetup extends GameDSLStandaloneSetup {
  @Override
  public Injector createInjector() {
    GameDSLRuntimeModule _gameDSLRuntimeModule = new GameDSLRuntimeModule();
    GameDSLIdeModule _gameDSLIdeModule = new GameDSLIdeModule();
    return Guice.createInjector(Modules2.mixin(_gameDSLRuntimeModule, _gameDSLIdeModule));
  }
}
