/**
 * generated by Xtext 2.25.0
 */
package assignment2.ide;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class GameDSLIdeModule extends AbstractGameDSLIdeModule {
}
