/*
 * generated by Xtext 2.25.0
 */
package assignment2.validation

import assignment2.gameDSL.Game

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class GameDSLValidator extends AbstractGameDSLValidator {
	
//
//	@Check
//	def checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.name.charAt(0))) {
//			warning('Name should start with a capital', 
//					GameDSLPackage.Literals.GREETING__NAME,
//					INVALID_NAME)
//		}
//	}

	def checkIfCellDiesInUnderpopulation(Game game) {
		
	}
	def checkIfCellLiveInNextGeneration(Game game) {
		
	}
	def checkIfCellDiesInOverpopulation(Game game) {
		
	}
	
}
