/**
 * generated by Xtext 2.25.0
 */
package assignment2.validation;

import assignment2.gameDSL.Game;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class GameDSLValidator extends AbstractGameDSLValidator {
  public Object checkIfCellDiesInUnderpopulation(final Game game) {
    return null;
  }
  
  public Object checkIfCellLiveInNextGeneration(final Game game) {
    return null;
  }
  
  public Object checkIfCellDiesInOverpopulation(final Game game) {
    return null;
  }
}
